@extends('layouts.master')
@section('content')
<style>.company-bill-form .purchase-items-table{width:100%;min-width:1050px;table-layout:fixed}.company-bill-form .purchase-items-table th,.company-bill-form .purchase-items-table td{vertical-align:middle}.company-bill-form .purchase-items-table th:nth-child(1),.company-bill-form .purchase-items-table td:nth-child(1){width:6% !important}.company-bill-form .purchase-items-table th:nth-child(2),.company-bill-form .purchase-items-table td:nth-child(2){width:24% !important}.company-bill-form .purchase-items-table th:nth-child(3),.company-bill-form .purchase-items-table td:nth-child(3){width:15% !important}.company-bill-form .purchase-items-table th:nth-child(4),.company-bill-form .purchase-items-table td:nth-child(4){width:12% !important}.company-bill-form .purchase-items-table th:nth-child(5),.company-bill-form .purchase-items-table td:nth-child(5){width:12% !important}.company-bill-form .purchase-items-table th:nth-child(6),.company-bill-form .purchase-items-table td:nth-child(6){width:14% !important}.company-bill-form .purchase-items-table th:nth-child(7),.company-bill-form .purchase-items-table td:nth-child(7){width:9% !important}.company-bill-form .purchase-items-table th:nth-child(8),.company-bill-form .purchase-items-table td:nth-child(8){width:8% !important}.company-bill-form .purchase-items-table input{width:100%;min-width:0}</style>
<div class="main-content company-bill-form" style="background:#eef3f9;min-height:100vh"><div class="container-fluid p-4"><div class="d-flex justify-content-between mb-4"><div><h1 class="fw-bold">{{ isset($bill) ? 'Edit Company Purchase Bill' : 'Add Company Purchase Bill' }}</h1><p class="text-muted">Enter the bill received after purchasing from a company.</p></div><div class="d-flex gap-2 align-items-start"><input type="file" id="companyBillDocument" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" hidden><button type="button" class="btn btn-success" id="fillCompanyBill"><i class="fa fa-file-arrow-up me-1"></i>Fill Invoice by Document</button><a href="{{ route('vat-system.company-bills.index') }}" class="btn btn-outline-secondary">Back</a></div></div>
<div id="companyBillScanStatus" class="alert alert-info d-none"></div>@if($errors->any())<div class="alert alert-danger">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
<form method="post" action="{{ isset($bill) ? route('vat-system.company-bills.update',$bill) : route('vat-system.company-bills.store') }}">@csrf @if(isset($bill)) @method('PUT') @endif
<div class="card mb-4"><div class="card-header bg-primary text-white fw-bold">Company / Supplier Details</div><div class="card-body"><div class="row g-3"><div class="col-md-4"><label>Company Name *</label><input name="company_name" class="form-control" value="{{ old('company_name',$bill->company_name ?? '') }}" required></div><div class="col-md-2"><label>VAT No.</label><input name="company_vat_no" class="form-control" value="{{ old('company_vat_no',$bill->company_vat_no ?? '') }}"></div><div class="col-md-2"><label>PAN No.</label><input name="company_pan_no" class="form-control" value="{{ old('company_pan_no',$bill->company_pan_no ?? '') }}"></div><div class="col-md-4"><label>Phone</label><input name="company_phone" class="form-control" value="{{ old('company_phone',$bill->company_phone ?? '') }}"></div><div class="col-md-6"><label>Address</label><input name="company_address" class="form-control" value="{{ old('company_address',$bill->company_address ?? '') }}"></div><div class="col-md-2"><label>Bill No. *</label><input name="bill_no" class="form-control" value="{{ old('bill_no',$bill->bill_no ?? '') }}" required></div><div class="col-md-2"><label>Bill Date *</label><input type="date" name="bill_date" class="form-control" value="{{ old('bill_date',isset($bill)?$bill->bill_date->format('Y-m-d'):now()->format('Y-m-d')) }}" required></div><div class="col-md-2"><label>Payment Mode</label><input name="payment_mode" class="form-control" value="{{ old('payment_mode',$bill->payment_mode ?? 'BANK ACCOUNT') }}"></div></div></div></div>
<div class="card mb-4"><div class="card-header bg-primary text-white fw-bold d-flex justify-content-between">Purchased Items <button type="button" class="btn btn-light btn-sm" id="addRow">+ Add Item</button></div><div class="table-responsive"><table class="table align-middle mb-0 purchase-items-table" id="items"><thead><tr><th>#</th><th>Particulars *</th><th>H.S. Code</th><th>Unit *</th><th>Qty *</th><th>Rate *</th><th>VAT</th><th></th></tr></thead><tbody>@if(isset($bill))@foreach($bill->items as $i=>$item)<tr><td class="sn">{{ $i+1 }}</td><td><input name="items[{{ $i }}][item_name]" class="form-control" value="{{ $item->item_name }}" required></td><td><input name="items[{{ $i }}][hs_code]" class="form-control" value="{{ $item->hs_code }}"></td><td><input name="items[{{ $i }}][unit]" class="form-control" value="{{ $item->unit }}" required></td><td><input name="items[{{ $i }}][quantity]" class="form-control qty" type="number" step=".001" value="{{ $item->quantity }}" required></td><td><input name="items[{{ $i }}][rate]" class="form-control rate" type="number" step=".01" value="{{ $item->rate }}" required></td><td><input name="items[{{ $i }}][is_taxable]" value="1" type="checkbox" @checked($item->is_taxable)></td><td><button type="button" class="btn btn-outline-danger remove"><i class="fa fa-trash"></i></button></td></tr>@endforeach @else<tr><td class="sn">1</td><td><input name="items[0][item_name]" class="form-control" required></td><td><input name="items[0][hs_code]" class="form-control"></td><td><input name="items[0][unit]" class="form-control" value="KG" required></td><td><input name="items[0][quantity]" class="form-control qty" type="number" step=".001" value="1" required></td><td><input name="items[0][rate]" class="form-control rate" type="number" step=".01" required></td><td><input name="items[0][is_taxable]" value="1" type="checkbox" checked></td><td><button type="button" class="btn btn-outline-danger remove"><i class="fa fa-trash"></i></button></td></tr>@endif</tbody></table></div></div>
<div class="row"><div class="col-md-8"><textarea name="notes" class="form-control" rows="3" placeholder="Notes">{{ old('notes',$bill->notes ?? '') }}</textarea></div><div class="col-md-4"><div class="card p-3"><div class="d-flex justify-content-between">Total <strong id="purchaseTotal">0.00</strong></div><div class="d-flex justify-content-between">VAT (13%) <strong id="purchaseVat">0.00</strong></div><hr><div class="d-flex justify-content-between fw-bold">Grand Total <strong id="purchaseGrand">0.00</strong></div><button class="btn btn-primary w-100 mt-3">{{ isset($bill) ? 'Update Company Bill' : 'Save Company Bill' }}</button></div></div></div></form></div></div>
<script>document.addEventListener('DOMContentLoaded',()=>{const b=document.querySelector('#items tbody');const total=()=>{let t=0,tax=0;b.querySelectorAll('tr').forEach(r=>{let a=(+r.querySelector('.qty').value||0)*(+r.querySelector('.rate').value||0);t+=a;if(r.querySelector('[type=checkbox]').checked)tax+=a});document.querySelector('#purchaseTotal').textContent=t.toFixed(2);document.querySelector('#purchaseVat').textContent=(tax*.13).toFixed(2);document.querySelector('#purchaseGrand').textContent=(t+tax*.13).toFixed(2)};const re=()=>b.querySelectorAll('tr').forEach((r,i)=>{r.querySelector('.sn').textContent=i+1;r.querySelectorAll('[name]').forEach(x=>x.name=x.name.replace(/items\[\d+\]/,'items['+i+']'))});document.querySelector('#addRow').onclick=()=>{let r=b.querySelector('tr').cloneNode(true);r.querySelectorAll('input').forEach(x=>{if(x.type==='checkbox')x.checked=true;else x.value=x.classList.contains('qty')?'1':''});b.append(r);re();total()};b.addEventListener('click',e=>{if(e.target.closest('.remove')&&b.children.length>1){e.target.closest('tr').remove();re();total()}});b.addEventListener('input',total);b.addEventListener('change',total);total()});</script>
@vite('resources/js/bill-ocr.js')
<script>
document.addEventListener('DOMContentLoaded',function(){const button=document.querySelector('#fillCompanyBill'),fileInput=document.querySelector('#companyBillDocument'),status=document.querySelector('#companyBillScanStatus'),body=document.querySelector('#items tbody');const recalc=()=>{let total=0,taxable=0;body.querySelectorAll('tr').forEach(row=>{const amount=(+row.querySelector('.qty').value||0)*(+row.querySelector('.rate').value||0);total+=amount;if(row.querySelector('[type=checkbox]').checked)taxable+=amount});document.querySelector('#purchaseTotal').textContent=total.toFixed(2);document.querySelector('#purchaseVat').textContent=(taxable*.13).toFixed(2);document.querySelector('#purchaseGrand').textContent=(total+taxable*.13).toFixed(2)};body.addEventListener('input',recalc);body.addEventListener('change',recalc);const show=(m,c)=>{status.className='alert alert-'+c;status.textContent=m};button.addEventListener('click',()=>fileInput.click());fileInput.addEventListener('change',async()=>{const file=fileInput.files[0];if(!file)return;if(file.size>10*1024*1024){show('Document must be 10 MB or smaller.','danger');return}const original=button.innerHTML;button.disabled=true;button.innerHTML='<span class="spinner-border spinner-border-sm"></span> Reading...';show('Reading the document locally. Please wait...','info');try{if(!window.BillOCR)throw new Error('OCR module did not load. Refresh the page and try again.');const invoice=await window.BillOCR.extract(file);if(invoice.supplier_name)document.querySelector('[name="company_name"]').value=invoice.supplier_name;if(invoice.bill_no)document.querySelector('[name="bill_no"]').value=invoice.bill_no;if(invoice.invoice_date)document.querySelector('[name="bill_date"]').value=invoice.invoice_date;const template=body.querySelector('tr').cloneNode(true);body.innerHTML='';(invoice.items||[]).slice(0,12).forEach((item,i)=>{const row=template.cloneNode(true);row.querySelector('.sn').textContent=i+1;row.querySelectorAll('[name]').forEach(x=>x.name=x.name.replace(/items\[\d+\]/,'items['+i+']'));row.querySelector('input[name$="[item_name]"]').value=item.name||'';row.querySelector('input[name$="[unit]"]').value=item.unit||'pcs';row.querySelector('input[name$="[quantity]"]').value=item.quantity||1;row.querySelector('input[name$="[rate]"]').value=item.cost_rate||0;row.querySelector('input[name$="[hs_code]"]').value=item.hs_code||'';row.querySelector('input[type="checkbox"]').checked=true;body.appendChild(row)});if(!body.children.length)body.appendChild(template);recalc();show('Bill details filled from the document. Please review every field before saving.','success')}catch(e){show(e.message||'The document could not be read.','danger')}finally{button.disabled=false;button.innerHTML=original;fileInput.value=''}})});
</script>
@endsection


















