@extends('layouts.master')
@section('content')
<div class="main-content" style="background:#eef3f9;min-height:100vh"><div class="container-fluid p-4">
<div class="d-flex justify-content-between mb-4"><div><h1 class="fw-bold">Company Purchase Bills</h1><p class="text-muted mb-1">Bills received from companies and suppliers.</p><span class="badge text-bg-primary px-3 py-2"><i class="fa fa-building me-1"></i>Selected Firm: {{ $firm->name }}</span></div><div class="d-flex gap-2 align-self-start"><a href="{{ route('vat-system.firm.switch', ['next' => 'purchase']) }}" class="btn btn-outline-primary"><i class="fa fa-repeat me-1"></i>Change Firm</a><a href="{{ route('vat-system.company-bills.create') }}" class="btn btn-primary">+ Add Company Bill</a></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="bill-search-card"><i class="fa fa-search"></i><input id="companyBillSearch" type="search" value="{{ $search ?? '' }}" placeholder="Search by bill no., supplier, VAT or PAN..." autocomplete="off"><button type="button" id="clearCompanyBillSearch" aria-label="Clear search">&times;</button><span id="companyBillSearchStatus"></span></div>
<div class="card"><div class="table-responsive"><table class="table table-hover mb-0"><thead class="table-primary"><tr><th>Bill No.</th><th>Date</th><th>Company ID</th><th>Company</th><th>VAT/PAN</th><th class="text-end">Grand Total (VAT Included)</th><th>Actions</th></tr></thead><tbody>
@forelse($bills as $bill)@php($total=$bill->items->sum(fn($i)=>(float)$i->quantity*(float)$i->rate))@php($taxable=$bill->items->where('is_taxable',true)->sum(fn($i)=>(float)$i->quantity*(float)$i->rate))@php($grand=$total+round($taxable*.13,2))
<tr><td><strong>#{{ $bill->bill_no }}</strong></td><td>{{ $bill->bill_date->format('Y-m-d') }}</td><td>{{ $bill->supplier_id ? '#'.$bill->supplier_id : '-' }}</td><td>{{ $bill->company_name }}</td><td>{{ $bill->company_vat_no ?: ($bill->company_pan_no ?: '-') }}</td><td class="text-end fw-bold">{{ number_format($grand,2) }}</td><td><a href="{{ route('vat-system.company-bills.show',$bill) }}" class="btn btn-info btn-sm text-white">View</a> <a href="{{ route('vat-system.company-bills.edit',$bill) }}" class="btn btn-warning btn-sm">Edit</a><form class="d-inline" method="post" action="{{ route('vat-system.company-bills.destroy',$bill) }}" onsubmit="return confirm('Delete this company bill?')">@csrf @method('DELETE')<button class="btn btn-danger btn-sm">Delete</button></form></td></tr>
@empty<tr><td colspan="7" class="text-center p-5">No purchase bills saved for {{ $firm->name }}.</td></tr>@endforelse
</tbody></table></div><div class="p-3">{{ $bills->links() }}</div></div></div></div>
<style>
.bill-search-card{position:relative;display:flex;align-items:center;gap:10px;background:#fff;border:1px solid #cbd9eb;border-radius:12px;padding:8px 14px;margin:0 0 16px;box-shadow:0 5px 16px rgba(23,59,114,.08)}
.bill-search-card>i{color:#1769ff;font-size:17px}.bill-search-card input{flex:1;border:0;outline:0;color:#173b72;font-size:16px;padding:8px 2px}.bill-search-card input::placeholder{color:#8292aa}.bill-search-card:focus-within{border-color:#1769ff;box-shadow:0 0 0 3px rgba(23,105,255,.14)}.bill-search-card button{display:none;border:0;background:#eaf1ff;color:#1769ff;border-radius:50%;width:28px;height:28px;font-size:22px;line-height:20px}.bill-search-card button.show{display:block}.bill-search-card span{font-size:12px;color:#64748b;white-space:nowrap}.company-bills-loading{opacity:.45;pointer-events:none}
</style>
<script>
document.addEventListener('DOMContentLoaded', function () {
    const input=document.getElementById('companyBillSearch'), clear=document.getElementById('clearCompanyBillSearch'), status=document.getElementById('companyBillSearchStatus'), table=document.querySelector('.table'), body=table?.querySelector('tbody'), card=table?.closest('.card');
    if(!input||!body||!card)return;
    let timer, controller;
    const esc=value=>String(value??'').replace(/[&<>'"]/g, character=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[character]));
    const render=items=>{body.innerHTML=items.length?items.map(b=>{const total=Number(b.total)||0,taxable=Number(b.taxable)||0,grand=total+Math.round(taxable*.13*100)/100;return `<tr><td><strong>#${esc(b.bill_no)}</strong></td><td>${esc(b.date)}</td><td>${b.supplier_id?'#'+esc(b.supplier_id):'-'}</td><td>${esc(b.company_name)}</td><td>${esc(b.vat_pan)}</td><td class="text-end fw-bold">${grand.toFixed(2)}</td><td><a href="${esc(b.show_url)}" class="btn btn-info btn-sm text-white">View</a> <a href="${esc(b.edit_url)}" class="btn btn-warning btn-sm">Edit</a></td></tr>`}).join(''):`<tr><td colspan="7" class="text-center p-5">No purchase bills match your search.</td></tr>`};
    const search=()=>{const q=input.value.trim();clear.classList.toggle('show',!!q);if(controller)controller.abort();if(!q){location.href=location.pathname;return}controller=new AbortController();card.classList.add('company-bills-loading');status.textContent='Searching...';fetch(`${location.pathname}?search=${encodeURIComponent(q)}`,{headers:{Accept:'application/json'},signal:controller.signal}).then(r=>r.json()).then(data=>{render(data.items||[]);status.textContent=(data.total||0)+' result'+((data.total||0)===1?'':'s')}).catch(e=>{if(e.name!=='AbortError')status.textContent='Search failed'}).finally(()=>card.classList.remove('company-bills-loading'))};
    input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(search,250)});clear.addEventListener('click',()=>{input.value='';search();input.focus()});
});
</script>
@endsection
