@extends('layouts.master')

@section('content')
<style>
    .vat-home{background:#f1f5fb;min-height:calc(100vh - 70px)}
    .vat-hero{background:linear-gradient(135deg,#102f63 0%,#2563eb 100%);color:#fff;border-radius:22px;padding:38px 42px;box-shadow:0 15px 35px #102f6330}
    .vat-hero h1{font-size:clamp(30px,4vw,48px);font-weight:900;margin:0}.vat-hero p{color:#dbeafe;font-size:16px;margin:8px 0 0}.vat-hero-icon{width:76px;height:76px;display:grid;place-items:center;border-radius:20px;background:#ffffff1f;font-size:42px}
    .vat-section-title{color:#172554;font-weight:900;font-size:22px}.vat-card{height:100%;background:#fff;border:1px solid #e3eaf5;border-radius:18px;padding:24px;box-shadow:0 8px 24px #18365d12;transition:.2s}.vat-card:hover{transform:translateY(-3px);box-shadow:0 14px 30px #18365d20}.vat-card-icon{width:54px;height:54px;border-radius:15px;display:grid;place-items:center;font-size:24px;margin-bottom:18px}.vat-card h3{font-size:20px;font-weight:900;color:#172554}.vat-card p{font-size:13px;color:#64748b;min-height:40px}.vat-card .btn{font-weight:800}.vat-quick{background:#fff;border-radius:18px;padding:22px;box-shadow:0 8px 24px #18365d12}.vat-quick a{display:flex;align-items:center;gap:10px;text-decoration:none;color:#173b72;font-weight:800;padding:12px 14px;border-radius:10px}.vat-quick a:hover{background:#eff6ff}.bg-sales{background:#dbeafe;color:#2563eb}.bg-purchase{background:#dcfce7;color:#15803d}.bg-customer{background:#ede9fe;color:#7c3aed}.bg-stock{background:#fef3c7;color:#b45309}
</style>
<style>.selected-firm-badge{display:inline-block;margin-top:14px;padding:8px 14px;border:1px solid #bfdbfe;border-radius:999px;background:#ffffff1c;color:#fff;font-size:13px;font-weight:800}</style>
<div class="main-content vat-home"><div class="container-fluid p-3 p-md-4">
    <div class="vat-hero d-flex flex-wrap justify-content-between align-items-center mb-5"><div><div class="text-uppercase small fw-bold mb-2" style="letter-spacing:1.5px;color:#bfdbfe">Active VAT Firm</div><h1><i class="fa fa-building me-2"></i>{{ $firm->name }}</h1><p>Manage sales invoices, purchase bills, and VAT stock for this firm.</p></div><div class="vat-hero-icon"><i class="fa fa-receipt"></i></div></div>
    <div class="d-flex justify-content-end mb-3"><a href="{{ route('vat-system.firm.switch', ['next' => 'workspace']) }}" class="btn btn-outline-primary"><i class="fa fa-repeat me-1"></i>Change Firm</a></div>
    <h2 class="vat-section-title mb-3">What would you like to do?</h2>
    <div class="row g-4 mb-5">
        <div class="col-md-6 col-xl-3"><div class="vat-card"><div class="vat-card-icon bg-sales"><i class="fa fa-cart-shopping"></i></div><h3>Sales Invoice</h3><p>Create an invoice for goods sold to your customer with automatic 13% VAT.</p><a href="{{ route('vat-system.create') }}" class="btn btn-primary w-100">Create Sales Invoice</a><a href="{{ route('vat-system.bills.index') }}" class="btn btn-outline-primary w-100 mt-2">View Sales Invoices</a></div></div>
        <div class="col-md-6 col-xl-3"><div class="vat-card"><div class="vat-card-icon bg-purchase"><i class="fa fa-building"></i></div><h3>Purchase Bills</h3><p>Record bills received from companies and suppliers to add stock.</p><a href="{{ route('vat-system.company-bills.create') }}" class="btn btn-success w-100">Add Purchase Bill</a><a href="{{ route('vat-system.company-bills.index') }}" class="btn btn-outline-success w-100 mt-2">View Purchase Bills</a><a href="{{ route('vat-system.suppliers.index') }}" class="btn btn-outline-secondary w-100 mt-2">Manage Suppliers</a></div></div>
        <div class="col-md-6 col-xl-3"><div class="vat-card"><div class="vat-card-icon bg-customer"><i class="fa fa-users"></i></div><h3>VAT Customers</h3><p>Maintain customer names, PAN numbers, addresses, and contact details.</p><a href="{{ route('vat-system.customers.index') }}" class="btn btn-outline-primary w-100">Manage Customers</a></div></div>
        <div class="col-md-6 col-xl-3"><div class="vat-card"><div class="vat-card-icon bg-stock"><i class="fa fa-boxes-stacked"></i></div><h3>VAT Stock</h3><p>Monitor quantities, prices, low stock alerts, and adjustments.</p><a href="{{ route('vat-system.stock.index') }}" class="btn btn-warning w-100 text-dark">Open Stock System</a></div></div>
    </div>
<div class="vat-quick"><div class="d-flex justify-content-between align-items-center mb-2"><h3 class="vat-section-title mb-0">Quick Links</h3><span class="text-muted small">VAT workspace navigation</span></div><div class="row g-2"><div class="col-md-3"><a href="{{ route('vat-system.create') }}"><i class="fa fa-plus-circle text-primary"></i>New Sales Invoice</a></div><div class="col-md-3"><a href="{{ route('vat-system.company-bills.create') }}"><i class="fa fa-file-circle-plus text-success"></i>New Purchase Bill</a></div><div class="col-md-3"><a href="{{ route('vat-system.party-ledger.customers') }}"><i class="fa fa-book text-info"></i>Party Ledger</a></div><div class="col-md-3"><a href="{{ route('vat-system.stock.index') }}"><i class="fa fa-chart-line text-warning"></i>Check Current Stock</a></div></div></div>
</div></div>
<style>
.vat-system-shell .vat-hero h1,.vat-system-shell .vat-hero h1 i{color:#fff!important;text-shadow:0 2px 8px rgba(0,0,0,.2)!important}.vat-system-shell .vat-hero-icon{color:#fff!important}
</style>
@endsection
