@extends('layouts.master')
@section('content')
<style>
.confirm-page{background:#eef3f9;min-height:100vh;padding:24px}.confirm-actions{max-width:820px;margin:0 auto 16px;display:flex;justify-content:space-between;align-items:center;gap:12px}.balance-editor{display:flex;align-items:end;gap:8px}.balance-editor label{font-size:11px;font-weight:700;color:#23436c}.balance-editor input{width:120px;font-size:13px}.confirm-letter{max-width:820px;min-height:1080px;margin:auto;background:#fff;padding:28px 34px;box-shadow:0 8px 30px #173b7222;color:#1e293b;border-top:4px solid #d5a727;font-family:Arial,sans-serif;box-sizing:border-box}.confirm-brand{display:grid;grid-template-columns:88px 1fr;align-items:center;border-bottom:2px solid #d5a727;padding:4px 0 14px}.confirm-logo{height:55px;width:55px;border:2px solid #174f86;border-radius:50%;display:grid;place-items:center;color:#174f86;font-family:Georgia,serif;font-weight:900;font-size:19px}.confirm-firm{text-align:center}.confirm-firm h1{font-family:Georgia,serif;font-size:23px;color:#0f3e73;margin:0;text-decoration:underline}.confirm-firm p{font-size:9px;margin:6px 0 0;color:#344a65}.confirm-title{text-align:center;margin:22px 0 18px;color:#9aa0a8;font-size:13px;font-weight:900;letter-spacing:2px}.confirm-date{text-align:right;font-size:10px;font-weight:800;margin-bottom:14px}.recipient{border-left:4px solid #155b99;padding:11px 13px;margin-bottom:14px;font-size:10px;line-height:1.65}.recipient-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px 40px}.recipient b,.subject b{font-size:9px;letter-spacing:.6px}.subject{border:1px solid #c8d8ea;border-radius:4px;padding:8px 13px;text-align:center;font-size:10px;margin:13px 0}.subject b{margin-right:22px;color:#74839a}.letter-text{font-size:10px;line-height:1.55;margin:14px 0}
.confirm-table-wrap{width:100%;max-width:100%;overflow:hidden}.confirm-letter table.confirm-table{display:table!important;width:100%!important;min-width:0!important;max-width:100%!important;table-layout:fixed!important;border-collapse:collapse!important;box-sizing:border-box}.confirm-letter .confirm-table thead{display:table-header-group!important;width:auto!important}.confirm-letter .confirm-table tbody{display:table-row-group!important;width:auto!important;word-wrap:normal!important}.confirm-letter .confirm-table tr{display:table-row!important;width:auto!important;table-layout:auto!important}.confirm-letter .confirm-table th,.confirm-letter .confirm-table td{display:table-cell!important;border:1px solid #a9c2df!important;padding:7px 5px!important;box-sizing:border-box;overflow-wrap:anywhere;word-break:break-word}.confirm-table th{background:#344bd2!important;color:#fff!important;text-align:left;font-size:12px;line-height:1.05;white-space:normal}.confirm-table td{font-size:11px}.confirm-table td:nth-child(n+3){text-align:right}.confirm-table .sales-row{font-weight:800;color:#0f3e73}.balance-box{border:1px solid #c8d8ea;border-radius:4px;margin-top:14px;font-size:10px}.balance-box h3{margin:0;padding:7px 12px;background:#f5f8fc;color:#0f3e73;font-size:9px;letter-spacing:.8px}.balance-row{padding:9px 12px;border-top:1px solid #dbe5f0;display:flex;justify-content:space-between}.notice{border-left:3px solid #d5a727;padding:8px 10px;font-size:9px;line-height:1.5;margin:15px 0 24px}.signatures{display:grid;grid-template-columns:1fr 1fr;gap:80px;margin-top:34px;font-size:9px}.signature-line{border-top:1px solid #173b72;padding-top:5px;font-weight:800}.signature-line small{display:block;margin-top:4px;font-weight:400;color:#65758a}.confirm-footer{border-top:1px solid #a9c2df;margin-top:30px;padding-top:8px;font-size:8px;display:flex;justify-content:space-between;color:#526579}@page{size:A4;margin:10mm}@media print{body *{visibility:hidden}.confirm-letter,.confirm-letter *{visibility:visible}.confirm-letter{position:absolute;left:0;top:0;width:100%;max-width:none;min-height:0;box-shadow:none;padding:18px 24px}.no-print{display:none!important}}
</style>
<div class="main-content confirm-page">
 <div class="no-print confirm-actions"><a href="{{ route('vat-system.party-ledger',$customer) }}" class="btn btn-outline-secondary">Back to Ledger</a><form method="GET" class="balance-editor"><label>Opening Balance<input type="number" name="opening_balance" min="0" step="0.01" value="{{ $openingBalance }}" class="form-control"></label><label>Closing Balance<input type="number" name="closing_balance" min="0" step="0.01" value="{{ $closingBalance }}" class="form-control"></label><button class="btn btn-outline-primary">Update</button><a href="{{ route('vat-system.balance-confirmation.pdf', ['customer' => $customer, 'fiscal_year' => $fiscalYear, 'opening_balance' => $openingBalance, 'closing_balance' => $closingBalance]) }}" class="btn btn-primary"><i class="fa fa-file-pdf me-1"></i>Print Letter (PDF)</a></form></div>
 <article class="confirm-letter">
  <header class="confirm-brand"><div class="confirm-logo">{{ strtoupper(substr($firm->name ?? 'VF',0,1)) }}{{ strtoupper(substr(str_replace(' ','',$firm->name ?? 'VF'),1,1)) }}</div><div class="confirm-firm"><h1>{{ $firm->name ?? 'VAT SYSTEM' }}</h1><p>{{ $firm->address ?? '' }}<br>VAT/PAN No: {{ $firm->pan_no ?? '-' }} &nbsp; | &nbsp; Contact: {{ $firm->phone ?? '-' }}</p></div></header>
  <h2 class="confirm-title">BALANCE CONFIRMATION<br>LETTER</h2><div class="confirm-date">DATE (B.S.) &nbsp; {{ $bsDate }}</div>
  <section class="recipient"><b>ADDRESSED TO</b><div class="recipient-grid"><div><b>PARTY NAME</b><br>{{ $customer->name }}</div><div><b>VAT NO.</b><br>{{ $customer->pan_no ?: '-' }}</div><div><b>ADDRESS</b><br>{{ $customer->address ?: '-' }}</div><div><b>PHONE</b><br>{{ $customer->phone ?: '-' }}</div></div></section>
  <div class="subject"><b>SUBJECT</b> Confirmation of Sales Transactions and Balance</div>
  <div class="letter-text">Dear Sir/Madam,<br><br>We hereby confirm that the following transaction details are recorded with our organization for the period <b>{{ $periodFrom ?: now()->toDateString() }} to {{ $periodTo ?: now()->toDateString() }}</b> <span style="color:#526579">(B.S. <b>{{ $periodFromBs }} to {{ $periodToBs }}</b>)</span>. Kindly verify the figures below and return a duly signed and stamped copy as confirmation of your acceptance.</div>
  <div class="confirm-table-wrap"><table class="confirm-table"><colgroup><col style="width:7%"><col style="width:21%"><col style="width:18%"><col style="width:18%"><col style="width:18%"><col style="width:18%"></colgroup><thead><tr><th>S.NO</th><th>PARTICULARS</th><th>EXEMPTED SALES</th><th>TAXABLE SALES</th><th>VAT 13%</th><th>TOTAL (NPR)</th></tr></thead><tbody><tr><td>1</td><td>Purchase</td><td>-</td><td>-</td><td>-</td><td>-</td></tr><tr><td>2</td><td>Purchase Return</td><td>-</td><td>-</td><td>-</td><td>-</td></tr><tr class="sales-row"><td>3</td><td>Sales</td><td>{{ $nonTaxableSales ? number_format($nonTaxableSales,2) : '-' }}</td><td>{{ $taxableSales ? number_format($taxableSales,2) : '-' }}</td><td>{{ $vatAmount ? number_format($vatAmount,2) : '-' }}</td><td>{{ number_format($total,2) }}</td></tr><tr><td>4</td><td>Sales Return</td><td>-</td><td>-</td><td>-</td><td>-</td></tr></tbody></table></div>
  <section class="balance-box"><h3>BALANCE SUMMARY</h3><div class="balance-row"><span>Opening balance at the beginning of the period</span><strong>{{ $openingBalance ? 'Rs '.number_format($openingBalance,2) : 'NIL' }}</strong></div><div class="balance-row"><span>Closing balance at the end of the period</span><strong>{{ $closingBalance ? 'Rs '.number_format($closingBalance,2) : 'NIL' }}</strong></div></section>
  <div class="notice">Please return a duly signed and stamped copy within seven days of receipt of this letter. Otherwise, the figures stated above will be considered accepted and confirmed.</div><div class="letter-text">Thanking you,<br><b>Yours faithfully</b></div><div class="signatures"><div class="signature-line">Authorized Signatory<small>For {{ $firm->name ?? 'Company' }}</small></div><div class="signature-line">Authorized Signatory<small>For {{ $customer->name }}</small></div></div><footer class="confirm-footer"><span>{{ $firm->name ?? 'VAT SYSTEM' }}</span><span>VAT CONFIRMATION</span></footer>
 </article>
</div>
@endsection
