<!doctype html>
<html>
<head>
<meta charset="utf-8">
<style>
@page{size:A4;margin:10mm}*{box-sizing:border-box}body{margin:0;color:#1e293b;font-family:Arial,sans-serif;font-size:10px}.letter{border-top:4px solid #d5a727;padding:28px 34px}.brand{display:block;min-height:75px;border-bottom:2px solid #d5a727;padding:4px 0 14px}.brand>.logo{float:left;width:88px;height:55px}.logo{height:55px;width:55px;border:2px solid #174f86;border-radius:50%;text-align:center;padding-top:16px;color:#174f86;font:bold 19px Georgia}.firm{text-align:center;margin-left:88px}.firm h1{margin:0;color:#0f3e73;font:700 23px Georgia;text-decoration:underline}.firm p{font-size:9px;margin:6px 0 0;color:#344a65}.title{text-align:center;margin:22px 0 18px;color:#0f3e73;font-size:13px;font-weight:900;letter-spacing:2px}.date{text-align:right;font-size:10px;font-weight:800;margin-bottom:14px}.recipient{border-left:4px solid #155b99;padding:11px 13px;margin-bottom:14px;font-size:10px;line-height:1.65}.grid{display:block;clear:both}.grid>div{float:left;width:50%;height:42px}.grid:after,.signatures:after{content:\"\";display:block;clear:both}.label{font-size:9px;font-weight:bold;letter-spacing:.6px}.subject{border:1px solid #c8d8ea;border-radius:4px;padding:8px 13px;text-align:center;font-size:10px;margin:13px 0}.text{font-size:10px;line-height:1.55;margin:14px 0}.data{width:100%;border-collapse:collapse;table-layout:fixed}.data th,.data td{border:1px solid #a9c2df;padding:7px 5px;overflow-wrap:anywhere;word-break:break-word}.data th{background:#344bd2;color:#fff;text-align:left;font-size:10px;line-height:1.05;-webkit-print-color-adjust:exact;print-color-adjust:exact}.data td{font-size:11px}.data td:nth-child(n+3){text-align:right}.data th:nth-child(1),.data td:nth-child(1){width:7%}.data th:nth-child(2),.data td:nth-child(2){width:21%}.data th:nth-child(n+3),.data td:nth-child(n+3){width:18%}.summary{border:1px solid #c8d8ea;margin-top:14px;font-size:10px}.summary h3{margin:0;padding:7px 12px;background:#f5f8fc;color:#0f3e73;font-size:9px;letter-spacing:.8px}.summary div{padding:9px 12px;border-top:1px solid #dbe5f0}.summary strong{float:right}.notice{border-left:3px solid #d5a727;padding:8px 10px;font-size:9px;line-height:1.5;margin:15px 0 24px}.signatures{display:block;clear:both;margin-top:34px;font-size:9px}.signature{float:left;width:50%;border-top:1px solid #173b72;padding-top:5px;font-weight:800}.signature small{display:block;margin-top:4px;font-weight:400;color:#65758a}
</style>
</head>
<body>
<article class="letter">
<header class="brand"><div class="logo">{{ strtoupper(substr($firm->name ?? 'VF',0,1)) }}{{ strtoupper(substr(str_replace(' ','',$firm->name ?? 'VF'),1,1)) }}</div><div class="firm"><h1>{{ $firm->name ?? 'VAT SYSTEM' }}</h1><p>{{ $firm->address ?? '' }}<br>VAT/PAN No: {{ $firm->pan_no ?? '-' }} &nbsp; | &nbsp; Contact: {{ $firm->phone ?? '-' }}</p></div></header>
<h2 class="title">BALANCE CONFIRMATION<br>LETTER</h2>
<div class="date">DATE (B.S.) &nbsp; {{ $bsDate }}</div>
<section class="recipient"><b>ADDRESSED TO</b><div class="grid"><div><span class="label">PARTY NAME</span><br>{{ $customer->name }}</div><div><span class="label">VAT NO.</span><br>{{ $customer->pan_no ?: '-' }}</div><div><span class="label">ADDRESS</span><br>{{ $customer->address ?: '-' }}</div><div><span class="label">PHONE</span><br>{{ $customer->phone ?: '-' }}</div></div></section>
<div class="subject"><b>SUBJECT</b> &nbsp; Confirmation of Sales Transactions and Balance</div>
<div class="text">Dear Sir/Madam,<br><br>We hereby confirm that the following transaction details are recorded with our organization for the period <b>{{ $periodFrom }} to {{ $periodTo }}</b> (B.S. <b>{{ $periodFromBs }} to {{ $periodToBs }}</b>). Kindly verify the figures below and return a duly signed and stamped copy as confirmation of your acceptance.</div>
<table class="data"><thead><tr><th>S.NO</th><th>PARTICULARS</th><th>EXEMPTED<br>SALES</th><th>TAXABLE<br>SALES</th><th>VAT 13%</th><th>TOTAL<br>(NPR)</th></tr></thead><tbody><tr><td>1</td><td>Purchase</td><td>-</td><td>-</td><td>-</td><td>-</td></tr><tr><td>2</td><td>Purchase Return</td><td>-</td><td>-</td><td>-</td><td>-</td></tr><tr><td>3</td><td>Sales</td><td>{{ $nonTaxableSales ? number_format($nonTaxableSales,2) : '-' }}</td><td>{{ $taxableSales ? number_format($taxableSales,2) : '-' }}</td><td>{{ $vatAmount ? number_format($vatAmount,2) : '-' }}</td><td>{{ number_format($total,2) }}</td></tr><tr><td>4</td><td>Sales Return</td><td>-</td><td>-</td><td>-</td><td>-</td></tr></tbody></table>
<section class="summary"><h3>BALANCE SUMMARY</h3><div>Opening balance at the beginning of the period <strong>{{ $openingBalance ? 'Rs '.number_format($openingBalance,2) : 'NIL' }}</strong></div><div>Closing balance at the end of the period <strong>{{ $closingBalance ? 'Rs '.number_format($closingBalance,2) : 'NIL' }}</strong></div></section>
<div class="notice">Please return a duly signed and stamped copy within seven days of receipt of this letter. Otherwise, the figures stated above will be considered accepted and confirmed.</div><div class="text">Thanking you,<br><b>Yours faithfully</b></div><div class="signatures"><div class="signature">Authorized Signatory<small>For {{ $firm->name ?? 'Company' }}</small></div><div class="signature">Authorized Signatory<small>For {{ $customer->name }}</small></div></div>
</article>
</body>
</html>
