@extends('layouts.master')
@section('content')
<style>
.ledger-page{background:#eef3f9;min-height:100vh;padding:25px}.ledger-shell{max-width:1100px;margin:auto}.ledger-actions{display:flex;justify-content:space-between;align-items:center;margin-bottom:15px}.ledger-actions .btn{font-weight:700}.ledger-paper{background:#fff;border-top:4px solid #d5a727;padding:25px 30px;box-shadow:0 8px 28px #173b7220}.firm-head{text-align:center;border-bottom:2px solid #064b9e;padding-bottom:12px}.firm-head h1{font:700 27px Georgia,serif;color:#073b78;margin:0;text-decoration:underline;text-underline-offset:7px}.firm-head p{font:700 12px Georgia,serif;color:#173b72;line-height:1.4;margin:9px 0 0}.ledger-title{text-align:center;color:#aaa;font:700 17px Georgia,serif;letter-spacing:1px;margin:16px 0 10px}.party-info{border-top:2px solid #064b9e;border-bottom:1px solid #b5cae3;padding:10px 4px;color:#173b72;font-weight:700}.party-info span{margin-right:35px}.currency{padding:8px 4px;font-weight:700}.ledger-table{width:100%;border-collapse:collapse;table-layout:fixed;font-family:Georgia,serif}.ledger-table th,.ledger-table td{border:1px solid #b5cae3;padding:10px 8px}.ledger-table th{background:#f5f8fc;color:#718096;text-align:center;font-size:12px}.ledger-table td{text-align:right;color:#173b72;font-size:12px}.ledger-table th:nth-child(1),.ledger-table td:nth-child(1){width:8%;text-align:center}.ledger-table th:nth-child(2),.ledger-table td:nth-child(2){width:17%;text-align:center}.ledger-table th:nth-child(3),.ledger-table td:nth-child(3){width:13%;text-align:center}.ledger-table th:nth-child(4),.ledger-table td:nth-child(4){width:22%}.ledger-table th:nth-child(5),.ledger-table td:nth-child(5){width:19%}.ledger-table th:nth-child(6),.ledger-table td:nth-child(6){width:21%}.ledger-table tbody tr:nth-child(even){background:#fbfdff}.total-row td{font-weight:700;color:#888}.ledger-empty{text-align:center;padding:50px;color:#718096;border:1px solid #b5cae3}.outstanding{text-align:right;padding:18px 4px 0;color:#64748b}.outstanding strong{display:block;color:#d92945;font-size:24px;margin-top:4px}@media(max-width:700px){.ledger-page{padding:14px}.ledger-paper{padding:18px 12px;overflow-x:auto}.ledger-table{min-width:800px}.ledger-actions{align-items:stretch;flex-direction:column-reverse;gap:10px}.ledger-actions .btn{width:100%}}@media print{.no-print{display:none!important}.ledger-page{padding:0;background:#fff}.ledger-paper{box-shadow:none;padding:8mm;border-top:3px solid #d5a727}.ledger-table th,.ledger-table td{padding:7px;font-size:10px}}\n+</style>
<style>.ledger-table{display:table!important;width:100%!important;table-layout:fixed!important}.ledger-table thead{display:table-header-group!important;width:auto!important}.ledger-table tbody{display:table-row-group!important;width:auto!important;word-wrap:normal!important}.ledger-table tr{display:table-row!important;width:auto!important}.ledger-table th,.ledger-table td{display:table-cell!important;box-sizing:border-box!important}</style>
<div class="main-content ledger-page"><div class="ledger-shell">
 <div class="no-print ledger-actions"><a href="{{ route('vat-system.party-ledger.customers') }}" class="btn btn-outline-secondary"><i class="fa fa-arrow-left me-1"></i>Back to Customers</a><div class="d-flex gap-2"><a href="{{ route('vat-system.balance-confirmation',$customer) }}" class="btn btn-success"><i class="fa fa-file-signature me-1"></i>Balance Confirmation</a><button onclick="window.print()" class="btn btn-primary"><i class="fa fa-print me-1"></i>Print Ledger</button></div></div>
 <article class="ledger-paper"><header class="firm-head"><h1>{{ strtoupper($firm->name) }}</h1><p>{{ $firm->address }}<br>VAT No: {{ $firm->pan_no }}<br>Contact No: {{ $firm->phone }}</p></header><h2 class="ledger-title">PARTY LEDGER</h2><div class="party-info"><span>Party Name: {{ strtoupper($customer->name) }}</span><span>Party VAT No: {{ $customer->pan_no ?: '-' }}</span><br>Currency&nbsp; : &nbsp;NPR</div>
 @if($rows->count())@php $taxable=$rows->sum(fn($row)=>$row['bill']->items->where('is_taxable',true)->sum(fn($item)=>(float)$item->quantity*(float)$item->rate));$vat=round($taxable*.13,2); @endphp<table class="ledger-table mt-3"><thead><tr><th>S.N</th><th>Date (B.S.)</th><th>Bill No</th><th>Taxable Amount (NPR)</th><th>VAT (13%) (NPR)</th><th>Total Amount (NPR)</th></tr></thead><tbody>@foreach($rows as $row)@php $bill=$row['bill'];$lineTaxable=$bill->items->where('is_taxable',true)->sum(fn($item)=>(float)$item->quantity*(float)$item->rate);$lineVat=round($lineTaxable*.13,2); @endphp<tr><td>{{ $loop->iteration }}</td><td>{{ \App\Support\NepaliDate::adToBsString($bill->bill_date->format('Y-m-d'),'en') }}</td><td>#{{ $bill->bill_no }}</td><td>{{ number_format($lineTaxable,2) }}</td><td>{{ number_format($lineVat,2) }}</td><td>{{ number_format($row['amount'],2) }}</td></tr>@endforeach<tr class="total-row"><td colspan="3">TOTAL</td><td>{{ number_format($taxable,2) }}</td><td>{{ number_format($vat,2) }}</td><td>{{ number_format($total,2) }}</td></tr></tbody></table><div class="outstanding">Total Outstanding<strong>Rs {{ number_format($total,2) }}</strong></div>@else<div class="ledger-empty mt-3">No sales transactions found for this customer in the selected firm.</div>@endif
 </article>
</div></div>
@endsection
