@extends('layouts.master')
@section('content')
<div class="main-content" style="background:#eef3f9;min-height:100vh"><div class="container-fluid p-4">
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="fw-bold mb-1">Purchase Party Ledger</h1><p class="text-muted mb-1">Company purchase bills and balance confirmations.</p><span class="badge text-bg-primary">{{ $firm->name }} - FY {{ $fiscalYear }}</span></div><div class="d-flex gap-2"><a href="{{ route('vat-system.purchase-party-ledger.print-all', ['fiscal_year'=>$fiscalYear]) }}" target="_blank" class="btn btn-success"><i class="fa fa-print me-1"></i>Print All Purchase Balances</a><a href="{{ route('vat-system.company-bills.index') }}" class="btn btn-outline-secondary">Purchase Bills</a><a href="{{ route('vat-system.index') }}" class="btn btn-outline-primary">VAT Dashboard</a></div></div>
<form method="GET" class="card card-body mb-3"><div class="d-flex align-items-end gap-2"><div><label class="form-label fw-bold">Financial Year</label><select name="fiscal_year" class="form-select">@foreach($fiscalYears as $value=>$label)<option value="{{ $value }}" @selected($value === $fiscalYear)>{{ $label }}</option>@endforeach</select></div><button class="btn btn-primary">Apply</button></div></form>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-primary"><tr><th>#</th><th>Company Name</th><th>Bills</th><th class="text-end">Purchase Total</th><th>Actions</th></tr></thead><tbody>
@forelse($companies as $item)<tr><td>{{ $loop->iteration }}</td><td class="fw-bold">{{ $item->name }}</td><td>{{ $item->bill_count }}</td><td class="text-end fw-bold">Rs {{ number_format($item->total, 2) }}</td><td><a href="{{ route('vat-system.purchase-party-ledger', ['company'=>$item->name, 'fiscal_year'=>$fiscalYear]) }}" target="_blank" class="btn btn-primary btn-sm"><i class="fa fa-book me-1"></i>Ledger</a><a href="{{ route('vat-system.purchase-party-ledger', ['company'=>$item->name, 'fiscal_year'=>$fiscalYear]) }}" target="_blank" class="btn btn-outline-dark btn-sm ms-1"><i class="fa fa-print me-1"></i>Print Ledger</a><a href="{{ route('vat-system.purchase-balance-confirmation', ['company'=>$item->name, 'fiscal_year'=>$fiscalYear]) }}" class="btn btn-outline-primary btn-sm ms-1"><i class="fa fa-file-signature"></i></a></td></tr>
@empty<tr><td colspan="5" class="text-center p-5">No company purchase bills found.</td></tr>@endforelse
</tbody></table></div></div></div></div>
@endsection
