<?php
namespace App\Http\Controllers;
use App\Models\CompanyBill;
use App\Models\VatSupplier;
use App\Models\VatStock;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
class CompanyBillController extends Controller
{
    public function __construct() { $this->middleware('auth'); }
    public function index(Request $request) { $firm=$this->firm(); if(!$firm)return redirect()->route('vat-system.firm.select',['next'=>'purchase']); $search=trim((string)$request->query('search')); $query=CompanyBill::where('firm_id',$firm->id)->with(['items','supplier'])->when($search!=='',fn($q)=>$q->where(function($q)use($search){$q->where('bill_no','like',"%{$search}%")->orWhere('company_name','like',"%{$search}%")->orWhere('company_vat_no','like',"%{$search}%")->orWhere('company_pan_no','like',"%{$search}%")->orWhereHas('supplier',fn($q)=>$q->where('name','like',"%{$search}%"));}))->latest('bill_date')->latest('id'); if($request->expectsJson())return response()->json(['items'=>$query->limit(100)->get()->map(fn($bill)=>['id'=>$bill->id,'bill_no'=>$bill->bill_no,'date'=>$bill->bill_date->format('Y-m-d'),'supplier_id'=>$bill->supplier_id,'company_name'=>$bill->company_name,'vat_pan'=>$bill->company_vat_no?:($bill->company_pan_no?:'-'),'total'=>$bill->items->sum(fn($i)=>(float)$i->quantity*(float)$i->rate),'taxable'=>$bill->items->where('is_taxable',true)->sum(fn($i)=>(float)$i->quantity*(float)$i->rate),'show_url'=>route('vat-system.company-bills.show',$bill),'edit_url'=>route('vat-system.company-bills.edit',$bill)]),'total'=>$query->count()]); $bills=$query->paginate(15)->withQueryString(); return view('vat-system.company-bills.index',compact('bills','firm','search')); }
    public function create() { $firm=$this->firm(); if(!$firm)return redirect()->route('vat-system.firm.select',['next'=>'purchase']); $suppliers=VatSupplier::orderBy('name')->get(); return view('vat-system.company-bills.form',compact('firm','suppliers')); }
    public function store(Request $request) { $firm=$this->firmOrRedirect('purchase'); $supplier=VatSupplier::where('name',$request->input('company_name'))->first(); $duplicateMessage=$this->duplicateSupplierBillMessage($supplier,$request->input('bill_no')); if($duplicateMessage)return back()->withInput()->withErrors(['bill_no'=>$duplicateMessage]); $billRules=$supplier ? [Rule::unique('company_bills','bill_no')->where(fn($q)=>$q->where('supplier_id',$supplier->id))] : []; $data=$this->validated($request,$billRules); $data['firm_id']=$firm->id; $data['supplier_id']=$supplier?->id; $bill=$this->saveBill($data); return redirect()->route('vat-system.company-bills.index')->with('success','Company purchase bill saved successfully.'); }
    public function show(CompanyBill $companyBill) { $this->ensureFirm($companyBill); $companyBill->load('items'); return view('vat-system.company-bills.show', ['bill'=>$companyBill]); }
    public function edit(CompanyBill $companyBill) { $this->ensureFirm($companyBill); $companyBill->load('items'); $firm=$this->firm(); $suppliers=VatSupplier::orderBy('name')->get(); return view('vat-system.company-bills.form',['bill'=>$companyBill, 'firm'=>$firm, 'suppliers'=>$suppliers]); }
    public function update(Request $request, CompanyBill $companyBill) { $this->ensureFirm($companyBill); $firm=$this->firmOrRedirect('purchase'); $supplier=VatSupplier::where('name',$request->input('company_name'))->first(); $duplicateMessage=$this->duplicateSupplierBillMessage($supplier,$request->input('bill_no'),$companyBill->id); if($duplicateMessage)return back()->withInput()->withErrors(['bill_no'=>$duplicateMessage]); $billRules=$supplier ? [Rule::unique('company_bills','bill_no')->where(fn($q)=>$q->where('supplier_id',$supplier->id))->ignore($companyBill->id)] : []; $data=$this->validated($request,$billRules); $data['firm_id']=$firm->id; $data['supplier_id']=$supplier?->id; $this->saveBill($data,$companyBill); return redirect()->route('vat-system.company-bills.index')->with('success','Company purchase bill updated successfully.'); }
    public function destroy(CompanyBill $companyBill) { $this->ensureFirm($companyBill); $companyBill->load('items'); DB::transaction(function()use($companyBill){foreach($companyBill->items as $item)$this->changeStock($item->item_name,$item->unit,-(float)$item->quantity,(float)$item->rate,'Purchase bill #'.$companyBill->bill_no.' deleted');$companyBill->delete();}); return back()->with('success','Company purchase bill deleted successfully.'); }
    private function validated(Request $request,array $billRules=[]): array { return $request->validate(['company_name'=>['required','string','max:150',Rule::exists('vat_suppliers','name')],'company_vat_no'=>['nullable','string','max:50'],'company_pan_no'=>['nullable','string','max:50'],'company_address'=>['nullable','string','max:255'],'company_phone'=>['nullable','string','max:30'],'bill_no'=>array_merge(['required','string','max:50'],$billRules),'bill_date'=>['required','date'],'payment_mode'=>['nullable','string','max:50'],'discount'=>['nullable','numeric','min:0'],'notes'=>['nullable','string','max:1000'],'items'=>['required','array','min:1'],'items.*.item_name'=>['required','string','max:200'],'items.*.hs_code'=>['nullable','string','max:50'],'items.*.unit'=>['required','string','max:30'],'items.*.quantity'=>['required','numeric','gt:0'],'items.*.rate'=>['required','numeric','min:0'],'items.*.is_taxable'=>['nullable','boolean']], ['bill_no.unique' => 'This bill number is already used for this supplier.']); }
    private function saveBill(array $data,?CompanyBill $bill=null): CompanyBill { return DB::transaction(function()use($data,$bill){ $bill ??= new CompanyBill; if($bill->exists)$bill->load('items'); if($bill->exists)foreach($bill->items as $old)$this->changeStock($old->item_name,$old->unit,-(float)$old->quantity,(float)$old->rate,'Purchase bill edit reversal'); $bill->fill(collect($data)->except('items')->merge(['discount'=>0,'added_by'=>$bill->exists?$bill->added_by:(session('user_email') ?: auth()->user()?->email)])->all()); $bill->save(); $bill->items()->delete(); foreach($data['items'] as $item){$saved=$bill->items()->create($item+['is_taxable'=>!array_key_exists('is_taxable',$item)||!empty($item['is_taxable'])]);$this->changeStock($saved->item_name,$saved->unit,(float)$saved->quantity,(float)$saved->rate,'Purchase bill #'.$bill->bill_no); } return $bill; }); }
    private function changeStock(string $name,string $unit,float $quantity,float $rate,string $reference): void { $stock=VatStock::firstOrCreate(['firm_id'=>$this->firm()->id,'item_name'=>trim($name),'unit'=>trim($unit)],['quantity'=>0,'purchase_rate'=>$rate,'sale_rate'=>$rate,'reorder_level'=>0]); $before=(float)$stock->quantity;$after=$before+$quantity;$stock->update(['quantity'=>$after,'purchase_rate'=>$rate]);$stock->movements()->create(['movement_type'=>$quantity>=0?'purchase':'purchase_reversal','quantity'=>abs($quantity),'rate'=>$rate,'reference'=>$reference,'user_email'=>session('user_email')?:auth()->user()?->email,'quantity_before'=>$before,'quantity_after'=>$after]); }
    private function firm() { return \App\Models\VatFirm::whereKey(session('vat_firm_id'))->where('is_active', true)->first(); }
    private function firmOrRedirect(string $next) { $firm=$this->firm(); if(!$firm) abort(redirect()->route('vat-system.firm.select',['next'=>$next])->with('error','Please select an active VAT firm before saving.')); return $firm; }
    private function duplicateSupplierBillMessage(?VatSupplier $supplier, mixed $billNo, ?int $ignoreId=null): ?string { if(!$supplier || trim((string)$billNo)==='') return null; $existing=CompanyBill::with('firm')->where('supplier_id',$supplier->id)->where('bill_no',$billNo)->when($ignoreId,fn($q)=>$q->whereKeyNot($ignoreId))->first(); if(!$existing)return null; return 'Bill number '.(string)$billNo.' for '.$supplier->name.' is already used in firm '.($existing->firm?->name ?? 'another firm').'.'; }
    private function ensureFirm(CompanyBill $bill): void { abort_unless($this->firm() && (int) $bill->firm_id === (int) $this->firm()->id, 404); }
}
